services:
  win10:
    image: dockurr/windows
    container_name: win10
    environment:
       DISK_SIZE: "64G"
       VERSION: "10l"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 9999:3923
      - 5900:5900
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./str_10:/storage
      - ./oem_10:/oem
#      - ./ltsc.iso:/custom.iso
#      - ./data_10:/data
    restart: always
    stop_grace_period: 2m
