services:
  win7:
    image: dockurr/windows
    container_name: win7
    environment:
       RAM_SIZE: "4G"
       DISK_SIZE: "16G"
       VERSION: "7e"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900
      - 9999:3923
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./str_7:/storage
#      - ./oem_7:/oem
      - ./data_7:/data
    restart: always
    stop_grace_period: 2m
