services:
  winxp:
    image: dockurr/windows
    container_name: winxp
    environment:
       RAM_SIZE: "2G"
       DISK_SIZE: "8G"
       VERSION: "xp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900
      - 9999:3923
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./str_xp:/storage
#      - ./oem_xp:/oem
#      - ./data_xp:/data
    restart: always
    stop_grace_period: 2m
